### ISSUE TITLE
Comment annoter une date-heure (ex : dd/mm/yyyy hh:min) ?

### ISSUE THREAD

**Issue by jmhus** [DrFabach/guide_annotation_medicaments#1]
Le guide ne précise pas comment annoter une date-heure de manière explicite

https://github.com/DrFabach/guide_annotation_medicaments/blob/f72b3b2b1c6ef847850acf40de3104c106b96cac/README.md?plain=1#L690C1-L695

Par exemple : `06/08/2023 09h44`

Faut-il annoter 

1. la date et l'heure séparement `06/08/2023` et `09h44`
2. `06/08/2023 09h44` ensemble 

J'ai privilégié la solution 2 pour l'instant

**Comment by DrFabach** [comment]
Effectivement, je vais le préciser, iil faut annoter ensemble solution 2 : 
`06/08/2023 09h44`

effa60b074eeab77932192e4131983aaefbb1b65
