### ISSUE TITLE
Date_relative absente dans doccano

### ISSUE THREAD

**Issue by jmhus** [DrFabach/guide_annotation_medicaments#4]
Je ne retrouve pas le tag "date_relative" dans Doccano alors que demandé dans la doc

"Annoter les dates relatives (dans 10 jours, il y a 6 mois ) comme des **"Date_relative"**."

![image](https://github.com/DrFabach/guide_annotation_medicaments/assets/150685868/037352ad-9ceb-4cd6-acef-dbcb67675d12)

**Comment by DrFabach** [comment]
Effectivement, il faut que je le rajoute, d'où les doirts admin :)

**Comment by DrFabach** [comment]
Done !
