### ISSUE TITLE
Revoir les niveaux de titrage

### ISSUE THREAD

**Issue by jmhus** [DrFabach/guide_annotation_medicaments#5]
Par exemple, actuellement, les entités à annoter sont en titre niveau 1 comme le titre principal.
Pour plus de clarté, un titre global "Entités à annoter" pourrait être présent avec des sous-titres pour chaque type d'entité. 
Ceci permettrait d'avoir une table des matières lisible.

**Comment by DrFabach** [comment]
Effectivement Done
