### ISSUE TITLE
Rendre plus lisible les entités à annoter avec \` au lieu de **"

### ISSUE THREAD

**Issue by jmhus** [DrFabach/guide_annotation_medicaments#6]
Actuellement, les tags à annoter (entité et relations) sont représentées dans le documentation à l'aide de guillements anglaises + gras. Exemple : `**"duree"**`

Ceci ne ressort pas bien à la lecture tant du md rendu en html que à la lecture du texte brut. De plus ceci n'est pas constant dans le texte (plusieurs occurences avec des `**` uniquement.

Suggestion : utiliser les accents graves de code \` pour entourer ceci. Ceci donnerai 

**"duree"** -> `duree`

**Comment by DrFabach** [comment]
done
